-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('LIST_CREATED', 'PURCHASE_FINALIZED', 'MEMBER_JOINED', 'ITEM_ADDED', 'BUDGET_ALERT', 'PANTRY_EXPIRING', 'LIST_NUDGE') NOT NULL;

-- AlterTable
ALTER TABLE `SentAlert` MODIFY `type` ENUM('LIST_CREATED', 'PURCHASE_FINALIZED', 'MEMBER_JOINED', 'ITEM_ADDED', 'BUDGET_ALERT', 'PANTRY_EXPIRING', 'LIST_NUDGE') NOT NULL;
